import {
    ElBadge,
    ElButton,
    ElCascader,
    ElCascaderPanel,
    ElConfigProvider,
    ElDatePicker,
    ElDivider,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElEmpty,
    ElForm,
    ElFormItem,
    ElIcon,
    ElImage,
    ElImageViewer,
    ElInput,
    ElInputNumber,
    ElLink,
    ElMessage,
    ElNotification,
    ElOption,
    ElOptionGroup,
    ElPageHeader,
    ElPagination,
    ElPopconfirm,
    ElPopover,
    ElProgress,
    ElScrollbar,
    ElSelect,
    ElSlider,
    ElSwitch,
    ElTabPane,
    ElTabs,
    ElTag,
    ElTimePicker,
    ElTimeSelect,
    ElTooltip,
    ElTree,
    ElUpload
} from 'element-plus'; // 需要的就导入

const components = [
    ElLink,
    ElPopconfirm,
    // ElAlert,
    // ElAside,
    // ElAutocomplete,
    // ElBacktop,
    ElBadge,
    // ElBreadcrumb,
    // ElBreadcrumbItem,
    ElButton,
    // ElButtonGroup,
    // ElCalendar,
    // ElCard,
    // ElCarousel,
    // ElCarouselItem,
    ElCascader,
    ElCascaderPanel,
    // ElCheckbox,
    // ElCheckboxButton,
    // ElCheckboxGroup,
    // ElCol,
    // ElCollapse,
    // ElCollapseItem,
    // ElCollapseTransition,
    // ElColorPicker,
    ElConfigProvider,
    // ElContainer,
    ElDatePicker,
    // ElDialog,
    ElDivider,
    ElDropdown,
    ElDropdownItem,
    ElDropdownMenu,
    ElEmpty,
    // ElFooter,
    ElForm,
    ElFormItem,
    // ElHeader,
    ElIcon,
    // ElImage,
    ElInput,
    ElInputNumber,
    // ElLink,
    // ElLoading,
    // ElMain,
    // ElMenu,
    // ElMenuItem,
    // ElMenuItemGroup,
    ElMessage,
    // ElMessageBox,
    ElNotification,
    ElOption,
    ElOptionGroup,
    ElPageHeader,
    ElPagination,
    ElPopover,
    ElProgress,
    // ElRadio,
    // ElRadioButton,
    // ElRadioGroup,
    // ElRate,
    // ElRow,
    ElScrollbar,
    ElSelect,
    ElSlider,
    // ElStep,
    // ElSteps,
    ElSwitch,
    // ElTable,
    // ElTableColumn,
    // ElTabPane,
    ElTabs,
    ElTag,
    // ElTimeline,
    // ElTimelineItem,
    ElTimePicker,
    ElTimeSelect,
    ElTooltip,
    // ElTransfer,
    ElTree,
    ElUpload,
    ElImage,
    ElImageViewer,
    ElTabPane
];

export default function globalRegister(app) {
    for (const component of components) {
        app.component(component.name, component);
    }
}
